apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: workshop
spec:
  type: LoadBalancer
  selector:
    role: backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
