apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: workshop
spec:
  type: LoadBalancer
  selector:
    role: frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
